/** Game catalog — lazy import map */
export const GAMES = [
  {
    id: 'cube-brawl',
    n: 1,
    title: 'Cube Brawl',
    blurb: 'Clear rivals with timed attacks',
    load: () => import('./games/cube-brawl.js'),
  },
  {
    id: 'relic-rush',
    n: 2,
    title: 'Relic Rush',
    blurb: 'Grab relics before time runs out',
    load: () => import('./games/relic-rush.js'),
  },
  {
    id: 'break-shot',
    n: 3,
    title: 'Break Shot',
    blurb: 'Smash every target block',
    load: () => import('./games/break-shot.js'),
  },
  {
    id: 'fuse-run',
    n: 4,
    title: 'Fuse Run',
    blurb: 'Plant charges, then get clear',
    load: () => import('./games/fuse-run.js'),
  },
  {
    id: 'hill-king',
    n: 5,
    title: 'Hill King',
    blurb: 'Hold the high pad',
    load: () => import('./games/hill-king.js'),
  },
  {
    id: 'guard-grab',
    n: 6,
    title: 'Guard Grab',
    blurb: 'Collect orbs, defend the stash',
    load: () => import('./games/guard-grab.js'),
  },
  {
    id: 'tag-chase',
    n: 7,
    title: 'Tag Chase',
    blurb: 'Catch the runners',
    load: () => import('./games/tag-chase.js'),
  },
  {
    id: 'edge-shove',
    n: 8,
    title: 'Edge Shove',
    blurb: 'Knock rivals off the platform',
    load: () => import('./games/edge-shove.js'),
  },
  {
    id: 'boss-cube',
    n: 9,
    title: 'Boss Cube',
    blurb: 'Short duel vs a bigger boss',
    load: () => import('./games/boss-cube.js'),
  },
  {
    id: 'point-storm',
    n: 10,
    title: 'Point Storm',
    blurb: 'Rack score until the buzzer',
    load: () => import('./games/point-storm.js'),
  },
];
